[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/1drie5/py-playground/blob/main/pytorch-campusx/4_pytorch_training_pipeline.ipynb)

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### train test split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### scaling

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[-1.10448838, -0.69261051, -1.1206498 , ..., -1.38138298,
        -0.3306307 , -0.54226016],
       [-1.33583465, -1.65128096, -1.32501631, ..., -0.80156468,
        -0.70658073, -0.33571249],
       [-0.28797214, -0.42781151, -0.34677101, ..., -0.99106848,
        -0.19066663, -0.65326573],
       ...,
       [-1.25560059,  0.18760099, -1.25223387, ..., -1.38138298,
        -1.54636519,  0.33529131],
       [-0.79545966, -2.04847946, -0.79045604, ..., -0.38984242,
         0.2145782 ,  0.07848739],
       [-1.05062099,  0.9599314 , -1.05732497, ..., -1.26921844,
        -1.06951083, -0.88576993]])

In [9]:
y_train

546    B
21     B
246    B
44     M
204    B
      ..
141    M
492    M
97     B
120    B
299    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,

### Numpy arrays to PyTorch tensors

In [12]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [13]:
X_train_tensor

tensor([[-1.1045, -0.6926, -1.1206,  ..., -1.3814, -0.3306, -0.5423],
        [-1.3358, -1.6513, -1.3250,  ..., -0.8016, -0.7066, -0.3357],
        [-0.2880, -0.4278, -0.3468,  ..., -0.9911, -0.1907, -0.6533],
        ...,
        [-1.2556,  0.1876, -1.2522,  ..., -1.3814, -1.5464,  0.3353],
        [-0.7955, -2.0485, -0.7905,  ..., -0.3898,  0.2146,  0.0785],
        [-1.0506,  0.9599, -1.0573,  ..., -1.2692, -1.0695, -0.8858]],
       dtype=torch.float64)

In [14]:
X_train_tensor.shape

torch.Size([455, 30])

In [15]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

In [ ]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss


### Important Parameters

In [ ]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [ ]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}  | Loss: {loss.item()}')

Epoch: 1  | Loss: 3.151397629739686
Epoch: 2  | Loss: 3.00071210991588
Epoch: 3  | Loss: 2.847871834846839
Epoch: 4  | Loss: 2.6817139258013305
Epoch: 5  | Loss: 2.5075065997280896
Epoch: 6  | Loss: 2.3287597415462344
Epoch: 7  | Loss: 2.1502970869106672
Epoch: 8  | Loss: 1.9620957061510906
Epoch: 9  | Loss: 1.7701743970028996
Epoch: 10  | Loss: 1.586997942261186
Epoch: 11  | Loss: 1.415122559280137
Epoch: 12  | Loss: 1.2576475902715132
Epoch: 13  | Loss: 1.1180430559217664
Epoch: 14  | Loss: 0.9997549710886068
Epoch: 15  | Loss: 0.9055745583868638
Epoch: 16  | Loss: 0.8364155326004383
Epoch: 17  | Loss: 0.7896374979902472
Epoch: 18  | Loss: 0.7598246720705808
Epoch: 19  | Loss: 0.7413625497301836
Epoch: 20  | Loss: 0.7298231982314957
Epoch: 21  | Loss: 0.7222615875724154
Epoch: 22  | Loss: 0.7169367399649141
Epoch: 23  | Loss: 0.7128869264878315
Epoch: 24  | Loss: 0.7095957983616601
Epoch: 25  | Loss: 0.7067862447421754


In [ ]:
model.weights

tensor([[-0.3049],
        [ 0.2143],
        [ 0.4561],
        [-0.0415],
        [ 0.1287],
        [ 0.3011],
        [ 0.1195],
        [-0.3073],
        [-0.2197],
        [-0.0305],
        [-0.2179],
        [ 0.2292],
        [-0.1830],
        [-0.1546],
        [ 0.0630],
        [-0.2030],
        [-0.1728],
        [ 0.0915],
        [ 0.0193],
        [ 0.3487],
        [ 0.5096],
        [-0.1298],
        [ 0.2587],
        [-0.1982],
        [ 0.2020],
        [-0.1831],
        [ 0.3163],
        [-0.4264],
        [-0.0983],
        [ 0.0339]], dtype=torch.float64, requires_grad=True)

In [ ]:
model.bias

tensor([-0.1840], dtype=torch.float64, requires_grad=True)

### Evaluation

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5220067501068115


# NN Module

In [44]:
import torch.nn as nn

class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

  def loss_function(self, y_pred, y):
    # clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

In [45]:
learning_rate = 0.1
epochs = 25

In [24]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor.float()) # Convert input to float32

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor.float()) # Convert target to float32

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad

  # zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}  | Loss: {loss.item()}')

Epoch: 1  | Loss: 0.7154337763786316
Epoch: 2  | Loss: 0.7028834223747253
Epoch: 3  | Loss: 0.6951874494552612
Epoch: 4  | Loss: 0.6902298331260681
Epoch: 5  | Loss: 0.6868141889572144
Epoch: 6  | Loss: 0.6842944622039795
Epoch: 7  | Loss: 0.6823236346244812
Epoch: 8  | Loss: 0.6807109713554382
Epoch: 9  | Loss: 0.6793471574783325
Epoch: 10  | Loss: 0.6781656742095947
Epoch: 11  | Loss: 0.6771237850189209
Epoch: 12  | Loss: 0.6761922836303711
Epoch: 13  | Loss: 0.6753506660461426
Epoch: 14  | Loss: 0.6745834350585938
Epoch: 15  | Loss: 0.6738793849945068
Epoch: 16  | Loss: 0.6732290983200073
Epoch: 17  | Loss: 0.6726258993148804
Epoch: 18  | Loss: 0.6720640659332275
Epoch: 19  | Loss: 0.671538770198822
Epoch: 20  | Loss: 0.6710464358329773
Epoch: 21  | Loss: 0.6705840229988098
Epoch: 22  | Loss: 0.6701486110687256
Epoch: 23  | Loss: 0.6697381734848022
Epoch: 24  | Loss: 0.6693506240844727
Epoch: 25  | Loss: 0.6689842939376831


## Improved Code

In [46]:
loss_function = nn.BCELoss()

In [48]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor.float())

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.float().reshape(-1, 1))

  # clear gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()
  '''
  # parameters update
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad

  # zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()
  '''
  # parameters update
  optimizer.zero_grad()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}  | Loss: {loss.item()}')

Epoch: 1  | Loss: 0.579382061958313
Epoch: 2  | Loss: 0.579382061958313
Epoch: 3  | Loss: 0.579382061958313
Epoch: 4  | Loss: 0.579382061958313
Epoch: 5  | Loss: 0.579382061958313
Epoch: 6  | Loss: 0.579382061958313
Epoch: 7  | Loss: 0.579382061958313
Epoch: 8  | Loss: 0.579382061958313
Epoch: 9  | Loss: 0.579382061958313
Epoch: 10  | Loss: 0.579382061958313
Epoch: 11  | Loss: 0.579382061958313
Epoch: 12  | Loss: 0.579382061958313
Epoch: 13  | Loss: 0.579382061958313
Epoch: 14  | Loss: 0.579382061958313
Epoch: 15  | Loss: 0.579382061958313
Epoch: 16  | Loss: 0.579382061958313
Epoch: 17  | Loss: 0.579382061958313
Epoch: 18  | Loss: 0.579382061958313
Epoch: 19  | Loss: 0.579382061958313
Epoch: 20  | Loss: 0.579382061958313
Epoch: 21  | Loss: 0.579382061958313
Epoch: 22  | Loss: 0.579382061958313
Epoch: 23  | Loss: 0.579382061958313
Epoch: 24  | Loss: 0.579382061958313
Epoch: 25  | Loss: 0.579382061958313


In [49]:
# model evaluation
with torch.no_grad():
  y_pred = model(X_test_tensor.float().reshape(-1, 30)) # Convert input to float32 and reshape
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor.float().reshape(-1, 1)).float().mean() # Convert target to float32 and reshape
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.8245614171028137
