[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/1drie5/py-playground/blob/main/pytorch-campusx/4_pytorch_training_pipeline.ipynb)

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### train test split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### scaling

In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
X_train

array([[ 1.47613418,  1.63935654,  1.49273137, ...,  0.97966702,
         1.21252106,  1.68476479],
       [-0.49635568, -1.59764279, -0.52337028, ..., -0.10667289,
         0.32246482, -0.43245494],
       [-0.59597638,  1.27918338, -0.57813775, ...,  0.09388217,
        -0.48682119, -0.04893438],
       ...,
       [ 0.11275374,  0.49728847,  0.10707327, ...,  0.12882737,
         0.17992913, -0.86660721],
       [-0.29426797, -1.2397492 , -0.36812716, ..., -1.19574763,
        -1.26601633, -1.02141217],
       [ 0.26076164, -0.85905984,  0.23884462, ...,  0.36280828,
         0.07540295,  0.01566468]])

In [10]:
y_train

33     M
527    B
445    B
168    M
67     B
      ..
209    B
556    B
86     M
309    B
227    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [11]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [12]:
y_train

array([1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,

### Numpy arrays to PyTorch tensors

In [13]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [16]:
X_train_tensor

tensor([[ 1.4761,  1.6394,  1.4927,  ...,  0.9797,  1.2125,  1.6848],
        [-0.4964, -1.5976, -0.5234,  ..., -0.1067,  0.3225, -0.4325],
        [-0.5960,  1.2792, -0.5781,  ...,  0.0939, -0.4868, -0.0489],
        ...,
        [ 0.1128,  0.4973,  0.1071,  ...,  0.1288,  0.1799, -0.8666],
        [-0.2943, -1.2397, -0.3681,  ..., -1.1957, -1.2660, -1.0214],
        [ 0.2608, -0.8591,  0.2388,  ...,  0.3628,  0.0754,  0.0157]],
       dtype=torch.float64)

In [17]:
X_train_tensor.shape

torch.Size([455, 30])

In [18]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

In [20]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss


### Important Parameters

In [21]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [34]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}  | Loss: {loss.item()}')

Epoch: 1  | Loss: 3.151397629739686
Epoch: 2  | Loss: 3.00071210991588
Epoch: 3  | Loss: 2.847871834846839
Epoch: 4  | Loss: 2.6817139258013305
Epoch: 5  | Loss: 2.5075065997280896
Epoch: 6  | Loss: 2.3287597415462344
Epoch: 7  | Loss: 2.1502970869106672
Epoch: 8  | Loss: 1.9620957061510906
Epoch: 9  | Loss: 1.7701743970028996
Epoch: 10  | Loss: 1.586997942261186
Epoch: 11  | Loss: 1.415122559280137
Epoch: 12  | Loss: 1.2576475902715132
Epoch: 13  | Loss: 1.1180430559217664
Epoch: 14  | Loss: 0.9997549710886068
Epoch: 15  | Loss: 0.9055745583868638
Epoch: 16  | Loss: 0.8364155326004383
Epoch: 17  | Loss: 0.7896374979902472
Epoch: 18  | Loss: 0.7598246720705808
Epoch: 19  | Loss: 0.7413625497301836
Epoch: 20  | Loss: 0.7298231982314957
Epoch: 21  | Loss: 0.7222615875724154
Epoch: 22  | Loss: 0.7169367399649141
Epoch: 23  | Loss: 0.7128869264878315
Epoch: 24  | Loss: 0.7095957983616601
Epoch: 25  | Loss: 0.7067862447421754


In [35]:
model.weights

tensor([[-0.3049],
        [ 0.2143],
        [ 0.4561],
        [-0.0415],
        [ 0.1287],
        [ 0.3011],
        [ 0.1195],
        [-0.3073],
        [-0.2197],
        [-0.0305],
        [-0.2179],
        [ 0.2292],
        [-0.1830],
        [-0.1546],
        [ 0.0630],
        [-0.2030],
        [-0.1728],
        [ 0.0915],
        [ 0.0193],
        [ 0.3487],
        [ 0.5096],
        [-0.1298],
        [ 0.2587],
        [-0.1982],
        [ 0.2020],
        [-0.1831],
        [ 0.3163],
        [-0.4264],
        [-0.0983],
        [ 0.0339]], dtype=torch.float64, requires_grad=True)

In [36]:
model.bias

tensor([-0.1840], dtype=torch.float64, requires_grad=True)

### Evaluation

In [37]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5220067501068115
