[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/1drie5/py-playground/blob/main/pytorch-campusx/5_pytorch_nn_module.ipynb)

## NN Module

In [3]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out


In [4]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.3383],
        [0.3644],
        [0.3262],
        [0.3408],
        [0.3401],
        [0.4174],
        [0.3941],
        [0.3822],
        [0.3591],
        [0.3528]], grad_fn=<SigmoidBackward0>)

In [6]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[-0.0666, -0.2531, -0.0354, -0.4250, -0.1398]], requires_grad=True)

In [8]:
# show model bias
model.linear.bias

Parameter containing:
tensor([-0.0740], requires_grad=True)

In [9]:
!pip install torchinfo

In [10]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Improved Code v1

In [11]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [12]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.4710],
        [0.4707],
        [0.4652],
        [0.4783],
        [0.4411],
        [0.4536],
        [0.4599],
        [0.4321],
        [0.4685],
        [0.4237]], grad_fn=<SigmoidBackward0>)

In [16]:
# show model weights
print(model.linear1.weight)
print(model.linear2.weight)

Parameter containing:
tensor([[-0.2834, -0.0406,  0.4374, -0.0069, -0.2144],
        [ 0.2811,  0.2211, -0.3717, -0.2037,  0.2217],
        [-0.2226, -0.1897, -0.2937,  0.2787, -0.2210]], requires_grad=True)
Parameter containing:
tensor([[-0.3916,  0.4273, -0.3544]], requires_grad=True)


In [18]:
# show model bias
print(model.linear1.bias)
print(model.linear2.bias)

Parameter containing:
tensor([ 0.0152, -0.0789,  0.0671], requires_grad=True)
Parameter containing:
tensor([-0.1990], requires_grad=True)


In [19]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Improved Code v2

In [20]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):

    out = self.network(features)

    return out

In [21]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.4625],
        [0.4279],
        [0.4434],
        [0.4434],
        [0.4686],
        [0.4635],
        [0.4389],
        [0.4328],
        [0.4757],
        [0.4442]], grad_fn=<SigmoidBackward0>)

In [24]:
# show model weights
print(model.network[0].weight) # Access the first linear layer in the sequential module
print(model.network[2].weight) # Access the second linear layer in the sequential module

Parameter containing:
tensor([[ 0.0849,  0.1705,  0.3102, -0.2781, -0.2984],
        [-0.0186,  0.3451, -0.3066,  0.3918,  0.3578],
        [-0.3436, -0.1665, -0.2390, -0.2968,  0.2956]], requires_grad=True)
Parameter containing:
tensor([[-0.5359, -0.4197, -0.0190]], requires_grad=True)


In [25]:
!pip install torchinfo

In [26]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00